import { configProviderIds } from '../../types.js'

export function buildRootHelp(): string {
  return [
    'yardmaster',
    'Unified AI CLI for prompt execution, terminal debugging, diff review, and provider-aware automation.',
    '',
    'Start here:',
    '  yardmaster "<prompt>"',
    '  npm test 2>&1 | yardmaster debug',
    '  yardmaster review --all',
    '  yardmaster providers doctor',
    '',
    'Common workflows:',
    '  run        Execute a prompt with provider routing, presets, and fallback.',
    '  design     Get frontend design feedback and UI recommendations.',
    '  debug      Diagnose terminal errors from stdin.',
    '  review     Review the current diff with one agent or all agents.',
    '  providers  Check provider availability and auth health.',
    '  presets    Save reusable run defaults for common setups.',
    '  config     Inspect and change config values.',
    '  update     Refresh the local yardmaster install.',
    '',
    'Examples:',
    '  yardmaster "summarize the current branch"',
    '  yardmaster run --preset headless-codex "explain this repo layout"',
    '  yardmaster design "review the onboarding hero and primary CTA hierarchy"',
    '  yardmaster run --prompt-file prompt.txt',
    '  npm test 2>&1 | yardmaster debug --provider claude',
    '  yardmaster review --all --base origin/main',
    '  yardmaster providers doctor --json',
    '',
    'Next commands:',
    '  yardmaster help run',
    '  yardmaster help design',
    '  yardmaster help review',
    '  yardmaster presets list',
    '  yardmaster config path',
    '',
    'Command reference:',
    '  yardmaster run [options] <prompt>',
    '  yardmaster design [options] <prompt>',
    '  yardmaster commit [options]',
    '  yardmaster debug [options]',
    '  yardmaster review [--all | --agent <id>] [--diff-file <path> | --staged | --base <ref>] [--json]',
    '  yardmaster review --json-schema',
    '  yardmaster update [--json] [--dry-run] [--force]',
    '  yardmaster providers list [--json]',
    '  yardmaster providers doctor [--provider <id>] [--json]',
    '  yardmaster config get [key] [--json]',
    '  yardmaster config set <key> <value> [--dry-run]',
    '  yardmaster config init [--dry-run] [--force]',
    '  yardmaster config path [--json]',
    '  yardmaster presets list [--json]',
    '  yardmaster presets get <name> [--json]',
    '  yardmaster presets set <name> [options] [--dry-run] [--force]',
    '  yardmaster presets delete <name> [--dry-run] [--force]',
    '  yardmaster presets use <name> [--dry-run]',
    '  yardmaster completion <bash|zsh|fish>',
    '',
    'Global flags:',
    '  -h, --help',
    '  --version',
    '  --json',
    '  --plain',
    '  --no-color',
    '  -q, --quiet',
    '  -v, --verbose',
    '  --no-input',
    '',
    'Help topics:',
    '  yardmaster help run',
    '  yardmaster help design',
    '  yardmaster help commit',
    '  yardmaster help debug',
    '  yardmaster help review',
    '  yardmaster help providers',
    '  yardmaster help config',
    '  yardmaster help presets',
    '  yardmaster help update',
    '  yardmaster help completion',
    '',
    `Providers: ${configProviderIds.join(', ')} (pi replaces one CLI: set YARDMASTER_PI_BACKEND, YARDMASTER_PI_MODEL).`,
  ].join('\n')
}
