export const runHelp = [
  'Usage: yardmaster run [options] <prompt>',
  'Execute a prompt with provider routing, config defaults, and machine-readable output modes.',
  '',
  'Common flows:',
  '  yardmaster run "summarize this repo"',
  '  yardmaster run --provider codex --no-fallback "generate release notes"',
  '  yardmaster run --preset headless-codex --json "list risky files"',
  '',
  'Options:',
  '  -p, --provider <claude|codex|cursor-agent|gemini|pi>',
  '  -m, --model <name>',
  '  -w, --workspace <path>',
  '  --mode <name>',
  '  --trust',
  '  --preset <name>',
  '  --prompt-file <path|->',
  '  --yolo',
  '  --include-directories <a,b,c>',
  '  --output-format <text|json|stream-json>',
  '  --print',
  '  --extensions <a,b,c>',
  '  --mcp <a,b,c>',
  '  --timeout-ms <n>',
  '  --no-fallback',
  '',
  'Config and precedence:',
  '  flags > YARDMASTER_* env vars > .yardmaster/config.json > ~/.config/yardmaster/config.json > defaults',
  '  Relevant env vars: YARDMASTER_PROVIDER, YARDMASTER_MODEL, YARDMASTER_PI_MODEL (default model when provider is pi), YARDMASTER_PI_BACKEND (pi substitutes this CLI: claude|codex|cursor-agent|gemini; default gemini), YARDMASTER_MODE, YARDMASTER_WORKSPACE, YARDMASTER_TRUST, YARDMASTER_TIMEOUT_MS, YARDMASTER_OUTPUT',
  '',
  'Recovery tips:',
  '  Use `yardmaster providers doctor` when a provider is unavailable or unauthenticated.',
  '  Use `--no-fallback` to isolate one provider while debugging a failure.',
  '  Use `yardmaster help config` to inspect supported defaults and config keys.',
  '  Use `--prompt-file <path>` for saved prompt text or `--prompt-file -` to read stdin.',
] as const

export const designHelp = [
  'Usage: yardmaster design [options] <prompt>',
  'Get frontend design feedback and implementation-aware UI recommendations through the normal provider pipeline.',
  '',
  'Common flows:',
  '  yardmaster design "review the pricing page hierarchy and CTA emphasis"',
  '  yardmaster design --provider codex --no-fallback "critique the dashboard empty state"',
  '  yardmaster design --prompt-file brief.txt --json',
  '',
  'Options:',
  '  -p, --provider <claude|codex|cursor-agent|gemini|pi>',
  '  -m, --model <name>',
  '  -w, --workspace <path>',
  '  --mode <name>',
  '  --trust',
  '  --preset <name>',
  '  --prompt-file <path|->',
  '  --yolo',
  '  --timeout-ms <n>',
  '  --no-fallback',
  '',
  'Config and precedence:',
  '  flags > YARDMASTER_* env vars > .yardmaster/config.json > ~/.config/yardmaster/config.json > defaults',
  '  Relevant env vars: YARDMASTER_PROVIDER, YARDMASTER_MODEL, YARDMASTER_PI_MODEL, YARDMASTER_PI_BACKEND, YARDMASTER_MODE, YARDMASTER_WORKSPACE, YARDMASTER_TRUST, YARDMASTER_TIMEOUT_MS, YARDMASTER_OUTPUT',
  '',
  'Recovery tips:',
  '  Pass the design brief directly or use `--prompt-file <path>` for longer review requests.',
  '  Use `--no-fallback` to isolate one provider while tuning recommendation quality.',
  '  Use `--json` when you need structured automation-friendly output.',
] as const

export const reviewHelp = [
  'Usage: yardmaster review [--all | --agent <codex|claude|gemini|cursor>] [--diff-file <path> | --staged | --base <ref>]',
  'Review repository changes with one agent or all agents and emit either human text or stable JSON.',
  '',
  'Common flows:',
  '  yardmaster review --all',
  '  yardmaster review --agent codex --staged',
  '  yardmaster review --all --base origin/main',
  '  yardmaster review --all --diff-file saved.patch --json',
  '',
  'Options:',
  '  --all',
  '  --agent <id>',
  '  --diff-file <path>',
  '  --staged',
  '  --base <ref>',
  '  --json-schema',
  '',
  'Environment:',
  '  YARDMASTER_REVIEW_TIMEOUT_MS — provider execution timeout per review agent (default 300000 ms, max 900000).',
  '',
  'Recovery tips:',
  '  Choose exactly one target: `--all` or `--agent <id>`.',
  '  Choose one diff source: default git diff, `--staged`, `--base <ref>`, or `--diff-file <path>`.',
  '  Run `git status` first if review says there are no changes or git diff resolution failed.',
  '  If a provider times out on large diffs, raise YARDMASTER_REVIEW_TIMEOUT_MS and retry.',
] as const

export const commitHelp = [
  'Usage: yardmaster commit [options]',
  'Reads staged git changes and generates a Conventional Commits message.',
  '  -a, --apply',
  '  -p, --provider <claude|codex|cursor-agent|gemini|pi>',
  '  -m, --model <name>',
  '  -w, --workspace <path>',
  '  --mode <name>',
  '  --trust',
  '  --preset <name>',
  '  --yolo',
  '  --timeout-ms <n>',
  '  --no-fallback',
] as const

export const debugHelp = [
  'Usage: yardmaster debug [options]',
  'Read terminal error output from stdin and return a diagnosis through the normal provider pipeline.',
  '',
  'Common flows:',
  '  npm test 2>&1 | yardmaster debug',
  '  cat error.log | yardmaster debug --provider claude --no-fallback',
  '  bun run build 2>&1 | yardmaster debug --json',
  '  yardmaster debug --input-file error.log --provider claude',
  '',
  'Options:',
  '  -p, --provider <claude|codex|cursor-agent|gemini|pi>',
  '  -m, --model <name>',
  '  -w, --workspace <path>',
  '  --mode <name>',
  '  --trust',
  '  --preset <name>',
  '  --input-file <path|->',
  '  --yolo',
  '  --timeout-ms <n>',
  '  --no-fallback',
  '',
  'Config and precedence:',
  '  flags > YARDMASTER_* env vars > .yardmaster/config.json > ~/.config/yardmaster/config.json > defaults',
  '  Relevant env vars: YARDMASTER_PROVIDER, YARDMASTER_MODEL, YARDMASTER_PI_MODEL, YARDMASTER_PI_BACKEND, YARDMASTER_MODE, YARDMASTER_WORKSPACE, YARDMASTER_TRUST, YARDMASTER_TIMEOUT_MS, YARDMASTER_OUTPUT',
  '',
  'Recovery tips:',
  '  Pipe stderr/stdout into debug instead of passing error text as argv.',
  '  If you need a single provider diagnosis, add `--provider <id> --no-fallback`.',
  '  Use `--input-file <path>` for saved logs or `--input-file -` to read stdin explicitly.',
] as const

export const updateHelp = [
  'Usage: yardmaster update [--json] [--dry-run] [--force]',
  'Refresh the local yardmaster install in place.',
  '',
  'What it runs:',
  '  1) bun run build',
  '  2) bun link',
  '',
  'Common flows:',
  '  yardmaster update',
  '  yardmaster update --dry-run',
  '  yardmaster update --force --json',
  '',
  'Next command:',
  '  yardmaster --version',
  '',
  'Safety:',
  '  Use `--dry-run` to preview the build/link plan.',
  '  Use `--force` to skip the confirmation prompt.',
] as const

export const providersHelp = [
  'Usage: yardmaster providers <subcommand>',
  'Inspect provider inventory and diagnose availability/auth issues before running prompts.',
  '',
  'Subcommands:',
  '  list [--json]',
  '  doctor [--provider <id>] [--show-identity] [--json]',
  '',
  'Common flows:',
  '  yardmaster providers list',
  '  yardmaster providers doctor',
  '  yardmaster providers doctor --provider codex --json',
  '',
  'Privacy:',
  '  Doctor output is safe to paste. Provider CLIs print the signed-in account',
  '  (claude auth status returns email, orgId, orgName); those values are',
  '  redacted and identityRedacted is true. Pass --show-identity to see them.',
  '',
  'Recovery tips:',
  '  Run `yardmaster providers doctor` before blaming prompt execution failures on the CLI.',
  '  Use `yardmaster providers list --json` when scripting provider selection.',
] as const

export const configHelp = [
  'Usage: yardmaster config <subcommand>',
  'Inspect and change persistent defaults that affect run/debug behavior.',
  '',
  'Subcommands:',
  '  get [key] [--json]',
  '  set <key> <value> [--dry-run]',
  '  init [--dry-run] [--force]',
  '  path [--json]',
  '',
  'Supported keys:',
  '  provider.default',
  '  provider.fallbackOrder',
  '  model.byProvider',
  '  mode.default',
  '  workspace.last',
  '  output.default',
  '  trust.default',
  '  runtime.timeoutMs',
  '',
  'Config locations and precedence:',
  '  User config: ~/.config/yardmaster/config.json',
  '  Project config: <repo>/.yardmaster/config.json',
  '  Precedence: flags > YARDMASTER_* env vars > project config > user config > defaults',
  '',
  'Supported env vars:',
  '  YARDMASTER_PROVIDER',
  '  YARDMASTER_MODEL',
  '  YARDMASTER_MODE',
  '  YARDMASTER_WORKSPACE',
  '  YARDMASTER_TRUST',
  '  YARDMASTER_TIMEOUT_MS',
  '  YARDMASTER_OUTPUT',
  '  YARDMASTER_STRICT_COMMANDS',
  '',
  'Common flows:',
  '  yardmaster config init',
  '  yardmaster config get provider.default',
  '  yardmaster config set provider.default codex --dry-run',
  '  yardmaster config path',
  '',
  'Safety:',
  '  Use `--dry-run` to preview config changes without writing the user config file.',
  '  `config init` asks before overwriting an existing user config unless you pass `--force`.',
] as const

export const presetsHelp = [
  'Usage: yardmaster presets <subcommand>',
  'Save reusable run defaults so repeated provider setups become one named preset.',
  '',
  'Subcommands:',
  '  list [--json]',
  '  get <name> [--json]',
  '  set <name> [--provider <id>] [--model <name>] [--mode <name>] [--trust] [--yolo] [--print]',
  '      [--include-directories <a,b,c>] [--output-format <text|json|stream-json>] [--extensions <a,b,c>] [--mcp <a,b,c>] [--default] [--dry-run] [--force]',
  '  delete <name> [--dry-run] [--force]',
  '  use <name> [--dry-run]',
  '',
  'Common flows:',
  '  yardmaster presets set headless-codex --provider codex --yolo --default --dry-run',
  '  yardmaster presets list',
  '  yardmaster presets use headless-codex',
  '',
  'Recovery tips:',
  '  Run `yardmaster presets list` if you are not sure which preset names exist.',
  '  Run `yardmaster presets get <name>` to inspect what a preset will apply before using it.',
  '',
  'Safety:',
  '  Use `--dry-run` to preview preset changes.',
  '  `presets set` asks before overwriting an existing preset unless you pass `--force`.',
  '  `presets delete` asks before deleting a preset unless you pass `--force`.',
] as const

export const completionHelp = [
  'Usage: yardmaster completion <bash|zsh|fish>',
  'Generate shell completion scripts for the current command surface.',
  '',
  'Common flows:',
  '  yardmaster completion bash > ~/.local/share/bash-completion/completions/yardmaster',
  '  yardmaster completion zsh > ~/.zfunc/_yardmaster',
  '  yardmaster completion fish > ~/.config/fish/completions/yardmaster.fish',
  '',
  'Install notes:',
  '  bash: source the generated file or restart your shell after writing it to your completions directory.',
  '  zsh: add the directory to `fpath` and run `autoload -U compinit && compinit` if needed.',
  '  fish: writing the file into `~/.config/fish/completions/` is enough for the next shell session.',
] as const
