import { configProviderIds } from '../../types.js'

export function buildRootHelp(): string {
  return [
    'genie',
    'Unified AI CLI for prompt execution, terminal debugging, diff review, and provider-aware automation.',
    '',
    'Start here:',
    '  genie "<prompt>"',
    '  npm test 2>&1 | genie debug',
    '  genie review --all',
    '  genie providers doctor',
    '',
    'Common workflows:',
    '  run        Execute a prompt with provider routing, presets, and fallback.',
    '  design     Get frontend design feedback and UI recommendations.',
    '  debug      Diagnose terminal errors from stdin.',
    '  review     Review the current diff with one agent or all agents.',
    '  providers  Check provider availability and auth health.',
    '  presets    Save reusable run defaults for common setups.',
    '  config     Inspect and change config values.',
    '  update     Refresh the local genie install.',
    '',
    'Examples:',
    '  genie "summarize the current branch"',
    '  genie run --preset headless-codex "explain this repo layout"',
    '  genie design "review the onboarding hero and primary CTA hierarchy"',
    '  genie run --prompt-file prompt.txt',
    '  npm test 2>&1 | genie debug --provider claude',
    '  genie review --all --base origin/main',
    '  genie providers doctor --json',
    '',
    'Next commands:',
    '  genie help run',
    '  genie help design',
    '  genie help review',
    '  genie presets list',
    '  genie config path',
    '',
    'Command reference:',
    '  genie run [options] <prompt>',
    '  genie design [options] <prompt>',
    '  genie commit [options]',
    '  genie debug [options]',
    '  genie review [--all | --agent <id>] [--diff-file <path> | --staged | --base <ref>] [--json]',
    '  genie review --json-schema',
    '  genie update [--json] [--dry-run] [--force]',
    '  genie providers list [--json]',
    '  genie providers doctor [--provider <id>] [--json]',
    '  genie config get [key] [--json]',
    '  genie config set <key> <value> [--dry-run]',
    '  genie config init [--dry-run] [--force]',
    '  genie config path [--json]',
    '  genie presets list [--json]',
    '  genie presets get <name> [--json]',
    '  genie presets set <name> [options] [--dry-run] [--force]',
    '  genie presets delete <name> [--dry-run] [--force]',
    '  genie presets use <name> [--dry-run]',
    '  genie completion <bash|zsh|fish>',
    '',
    'Global flags:',
    '  -h, --help',
    '  --version',
    '  --json',
    '  --plain',
    '  --no-color',
    '  -q, --quiet',
    '  -v, --verbose',
    '  --no-input',
    '',
    'Help topics:',
    '  genie help run',
    '  genie help design',
    '  genie help commit',
    '  genie help debug',
    '  genie help review',
    '  genie help providers',
    '  genie help config',
    '  genie help presets',
    '  genie help update',
    '  genie help completion',
    '',
    `Providers: ${configProviderIds.join(', ')} (pi replaces one CLI: set GENIE_PI_BACKEND, GENIE_PI_MODEL).`,
  ].join('\n')
}
